application: whatsnoisy
version: 1
runtime: python
api_version: 1

handlers:

- url: /dl
  static_dir: static
  
- url: /css
  static_dir: helper/css

- url: /sample.*
  script: /sample/sample.py
  
- url: /locationtrace.*
  script: /locationtrace/locationtrace.py
  
- url: /location.*
  script: /location/location.py

- url: .*
  script: main.py
